# Generated by Django 4.0.1 on 2024-01-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_fruits_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruits',
            options={'ordering': ['-fruit_name'], 'verbose_name': 'home_fruits'},
        ),
        migrations.AlterModelTable(
            name='fruits',
            table='home_fruits',
        ),
    ]
